import type { PlanSummary, TaskTreeNode } from "@the-planner/shared";

export const examplePlans: PlanSummary[] = [
  {
    id: "example-plan-evening-focus",
    title: "노래 만들기 > 코드진행",
    startAt: "2026-07-02T22:00:00.000Z",
    endAt: "2026-07-03T01:00:00.000Z",
    location: "작업실",
    memo: "수행 목표: DAW 진입 전 레퍼런스 곡조 분석 완료",
    estimatedCost: null,
    actualCost: null,
    supplies: [
      { id: "example-supply-headphone", title: "헤드폰", isChecked: true },
      { id: "example-supply-reference", title: "레퍼런스 트랙 3곡", isChecked: false },
    ],
    tasks: [
      { planTaskId: "example-plan-task-key", taskId: "example-task-key", title: "곡의 키 정하기", status: "todo", completedAt: null },
      { planTaskId: "example-plan-task-repeat", taskId: "example-task-repeat", title: "반복할 코드 정하기", status: "todo", completedAt: null },
      { planTaskId: "example-plan-task-voicing", taskId: "example-task-voicing", title: "코드 보이싱하기", status: "todo", completedAt: null },
    ],
  },
  {
    id: "example-plan-morning-admin",
    title: "개인 루틴 및 메일 점검",
    startAt: "2026-07-02T09:00:00.000Z",
    endAt: "2026-07-02T12:00:00.000Z",
    location: "집",
    memo: "오전 슬롯",
    estimatedCost: null,
    actualCost: null,
    supplies: [],
    tasks: [],
  },
  {
    id: "example-plan-afternoon-docs",
    title: "플래너 아키텍처 문서 작업",
    startAt: "2026-07-02T14:00:00.000Z",
    endAt: "2026-07-02T18:00:00.000Z",
    location: "카페",
    memo: "오후 슬롯",
    estimatedCost: null,
    actualCost: null,
    supplies: [],
    tasks: [],
  },
];

export const exampleTasks: TaskTreeNode[] = [
  {
    id: "example-task-song",
    parentId: null,
    type: "project",
    title: "노래 만들기",
    description: "하나의 곡을 완성 가능한 조각으로 나누기",
    why: "아이디어를 실제 결과물로 남기기 위해",
    level: 1,
    status: "active",
    targetStartAt: null,
    targetEndAt: null,
    progress: { leafTotalCount: 5, leafDoneCount: 1, progressRate: 0.2 },
    children: [
      {
        id: "example-task-beat",
        parentId: "example-task-song",
        type: "project",
        title: "비트 만들기",
        description: null,
        why: null,
        level: 2,
        status: "active",
        targetStartAt: null,
        targetEndAt: null,
        progress: { leafTotalCount: 2, leafDoneCount: 1, progressRate: 0.5 },
        children: [
          {
            id: "example-task-sample",
            parentId: "example-task-beat",
            type: "task",
            title: "샘플링 사운드 추출",
            description: null,
            why: null,
            level: 3,
            status: "done",
            targetStartAt: null,
            targetEndAt: null,
            progress: { leafTotalCount: 1, leafDoneCount: 1, progressRate: 1 },
            children: [],
          },
          {
            id: "example-task-rhythm",
            parentId: "example-task-beat",
            type: "task",
            title: "리듬 배치하기",
            description: null,
            why: null,
            level: 3,
            status: "todo",
            targetStartAt: null,
            targetEndAt: null,
            progress: { leafTotalCount: 1, leafDoneCount: 0, progressRate: 0 },
            children: [],
          },
        ],
      },
      {
        id: "example-task-chord",
        parentId: "example-task-song",
        type: "project",
        title: "코드진행 만들기",
        description: null,
        why: null,
        level: 2,
        status: "active",
        targetStartAt: null,
        targetEndAt: null,
        progress: { leafTotalCount: 3, leafDoneCount: 0, progressRate: 0 },
        children: [
          {
            id: "example-task-key",
            parentId: "example-task-chord",
            type: "task",
            title: "곡의 키 정하기",
            description: "DAW 진입 전 레퍼런스 곡조 분석 완료",
            why: null,
            level: 3,
            status: "todo",
            targetStartAt: null,
            targetEndAt: null,
            progress: { leafTotalCount: 1, leafDoneCount: 0, progressRate: 0 },
            children: [],
          },
          {
            id: "example-task-repeat",
            parentId: "example-task-chord",
            type: "task",
            title: "반복할 코드 정하기",
            description: null,
            why: null,
            level: 3,
            status: "todo",
            targetStartAt: null,
            targetEndAt: null,
            progress: { leafTotalCount: 1, leafDoneCount: 0, progressRate: 0 },
            children: [],
          },
          {
            id: "example-task-voicing",
            parentId: "example-task-chord",
            type: "task",
            title: "코드 보이싱하기",
            description: null,
            why: null,
            level: 3,
            status: "todo",
            targetStartAt: null,
            targetEndAt: null,
            progress: { leafTotalCount: 1, leafDoneCount: 0, progressRate: 0 },
            children: [],
          },
        ],
      },
    ],
  },
];